# -*- coding: utf-8 -*-
"""Training_yolov4_tiny.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10wV13bX5MxsRAMTUgTR-bnImjXnRnO2C
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/object_detection/'

!cp /mydrive/yolov4/generate_train.py

#creation of the train/test

import os 
image_path= "/content/drive/MyDrive/object_detection/custom_data"
os.chdir(image_path)

path_list = []
for current_dir,dirs,files in os.walk('.'):
    for f in files:
        if f.endswith('.jpg'):
            file_loc=image_path+ "/" + f
            path_list.append(file_loc + '\n')

path_list_test = path_list[:int(len(path_list)*0.2)]
path_list = path_list[int(len(path_list)*0.20):]

with open ('test.txt','w') as test:
    for i in path_list_test:
        test.write(i)

with open ('train.txt','w') as train:
    for i in path_list:
        train.write(i)

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

!make

!ls

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

!chmod +x darknet/darknet

!darknet/darknet detector train custom_data/labelled_data.data darknet/cfg/yolov4-tiny-custom.cfg custom_weight/yolov4-tiny.conv.29  -dont_show -map

# show chart.png of how custom object detector did with training

!darknet/darknet detector train custom_data/labelled_data.data darknet/cfg/yolov4-obj.cfg  custom_weight/yolov4.conv.137  -dont_show -map